window.produtividadeLessons = (window.produtividadeLessons || []).concat([
  {
    id: 'documentos-diagnostico', number: '00', menuTitle: 'O documento que não orienta',
    unit: 'Módulo 2 · Documentos Profissionais', technicalTitle: 'Diagnóstico · legibilidade, estrutura e destino',
    title: 'O documento existe, mas ninguém consegue usá-lo',
    objective: 'Diagnosticar problemas de um documento sem começar pela aparência nem apagar a fonte recebida.',
    content: `
      <div class="story-opening"><span class="eyebrow">Terça-feira · 8h10 · SEC-03</span><h2>A programação da Feira chegou como um bloco de texto com destaques feitos à mão.</h2><p>Marina precisa enviá-la às famílias e permitir que Paulo revise horários em <strong>COORD-02</strong>. Há títulos em maiúsculas, espaços usados para alinhar, uma tabela digitada com tabulações e uma imagem sem origem. O conteúdo pode estar correto, mas ainda não é uma entrega confiável.</p></div>
      <section class="decision-box"><h3>Investigue antes de “embelezar”</h3><p>Qual verificação deve vir primeiro?</p><div class="choice-list" data-choice data-answer="b" data-explanation="Finalidade, público e fonte determinam o que precisa ser corrigido; fonte, cor e borda vêm depois."><label><input type="radio" name="d200" value="a"> escolher uma paleta e uma fonte;</label><label><input type="radio" name="d200" value="b"> comparar o texto com P-00, identificar público, fonte e pendências;</label><label><input type="radio" name="d200" value="c"> exportar imediatamente para PDF.</label><button class="action-button" type="button" data-check-choice>Conferir decisão</button><div class="choice-result" aria-live="polite"></div></div></section>
      <h3>Laboratório · abrir sem perder a origem</h3><div class="task-box"><strong>Ferramenta principal: LibreOffice Writer</strong><ol><li>Baixe a <a href="../downloads/informatica-produtividade/modulo-02/minuta-programacao-feira.odt" download>minuta problemática da programação</a> e salve-a em <code>00_Entrada</code>.</li><li>Copie o arquivo para <code>10_Em_trabalho</code> e renomeie a cópia como <code>2026-09-08_programacao-feira_em-edicao_v01.odt</code>, seguindo P-02.</li><li>Abra a cópia no Writer. Se aparecer uma faixa de formato ou modo somente leitura, não a ignore: confirme que abriu a cópia <code>.odt</code> correta.</li><li>Use <strong>Arquivo → Propriedades</strong> e anote título, autor e estatísticas disponíveis; depois percorra o documento sem editar.</li><li>Compare datas, locais e responsáveis com P-00 e marque apenas sintomas observáveis.</li></ol></div>
      <div class="evidence-box"><strong>Resultado esperado</strong><p>Você encontra hierarquia visual inconsistente, alinhamento por espaços, tabela não estrutural, imagem sem legenda/fonte, uma pendência de horário e ausência de identificação da versão.</p><p><strong>Se divergir:</strong> feche sem salvar, confirme nome e pasta, baixe novamente e trabalhe na cópia. Não conclua que um dado está errado somente porque a formatação está ruim.</p></div>
      <div class="artifact-card"><strong>P-10 iniciado · diagnóstico</strong><span>Finalidade, público, problemas observados, riscos, fonte consultada e itens que ainda exigem confirmação.</span></div>
      <div class="bridge-box"><strong>Consequência</strong><p>Antes de corrigir o arquivo, a equipe precisa definir o que o documento deve permitir que o leitor encontre, compreenda e faça.</p></div>`
  },
  {
    id: 'documentos-finalidade', number: '01', menuTitle: 'Finalidade, público e critérios',
    unit: 'Módulo 2 · Documentos Profissionais', technicalTitle: 'Planejamento editorial · leitor, ação e aceite',
    title: 'Um documento serve a alguém e termina em uma ação',
    objective: 'Converter o pedido da Feira em critérios verificáveis de conteúdo, leitura e entrega.',
    content: `
      <div class="story-opening"><span class="eyebrow">Terça-feira · 8h40 · alinhamento com Paulo</span><h2>A mesma programação não atende do mesmo modo famílias e equipe interna.</h2><p>As famílias precisam de data, horário, local e orientação de entrada. A equipe interna precisa também de responsáveis, montagem e pendências. Paulo decide que haverá um documento público e uma fonte editável interna — não um único arquivo com informação escondida por cor.</p></div>
      <div class="table-wrap"><table><thead><tr><th>Pergunta</th><th>Decisão pública</th><th>Evidência de aceite</th></tr></thead><tbody><tr><td>Quem lê?</td><td>famílias e visitantes</td><td>linguagem direta, sem siglas internas</td></tr><tr><td>O que fará?</td><td>planejar chegada e localizar atividades</td><td>data, horários e locais visíveis</td></tr><tr><td>O que não pode sair?</td><td>telefones, notas e aprovações internas</td><td>comparação com a fonte interna</td></tr><tr><td>Como recebe?</td><td>PDF acessível e versão impressa</td><td>arquivo aberto e impressão conferida</td></tr></tbody></table></div>
      <h3>Aplicar · completar o cabeçalho de P-10</h3><div class="template-box"><label for="modelo-p10a"><strong>Modelo copiável</strong></label><textarea id="modelo-p10a" class="record-template" rows="13" readonly>P-10 — MODELO E CHECKLIST DE DOCUMENTO
Documento: Programação pública da Feira
Fonte de conteúdo: P-00 + confirmações registradas de Paulo
Público: famílias e visitantes
Ação esperada: saber quando chegar, onde entrar e quais atividades ocorrerão
Conteúdo obrigatório: título, data, horário, locais, programação e contato institucional
Conteúdo proibido: dados pessoais, notas internas e pendências
Formato de trabalho: ODT
Formato de entrega: PDF + impressão A4
Critérios: estrutura por estilos, leitura lógica, fontes identificadas, acessibilidade conferida e versão aprovada
Responsável por produzir: Marina
Responsável por aprovar: Paulo</textarea><div><button class="action-button" type="button" data-copy="#modelo-p10a">Copiar P-10</button><span class="copy-status" aria-live="polite"></span></div></div>
      <div class="task-box"><strong>Roteiro de decisão</strong><ol><li>Copie o modelo para o registro da equipe; não edite a versão exibida na página.</li><li>Compare cada campo com P-00 e a minuta recebida. Preencha somente o que possui fonte.</li><li>Marque divergências como pendência, indicando quem pode decidir e qual evidência será aceita.</li><li>Peça a um colega que diga o que será entregue, para quem e como será aceito usando apenas P-10.</li><li>Se a resposta depender de explicação oral, complete o registro e salve-o junto da versão de trabalho.</li></ol></div>
      <div class="note-box"><strong>Equivalentes essenciais</strong><p>No Word ou Google Documentos, procure estilos de título, comentários e exportação/baixar em PDF. Os nomes podem variar; o critério de saída não muda. Registre em P-10 qual ferramenta e versão foram usadas.</p></div>
      <div class="bridge-box"><strong>Próximo problema</strong><p>Os critérios estão claros, mas o texto ainda não possui uma ordem que ajude o leitor a localizar respostas. É preciso estruturar antes de formatar.</p></div>`
  },
  {
    id: 'documentos-estrutura', number: '02', menuTitle: 'Estrutura e hierarquia',
    unit: 'Módulo 2 · Documentos Profissionais', technicalTitle: 'Organização do conteúdo · seções e leitura',
    title: 'A ordem do conteúdo reduz perguntas e erros',
    objective: 'Organizar informações em uma hierarquia que expresse relações, não apenas diferenças de tamanho.',
    content: `
      <div class="story-opening"><span class="eyebrow">Terça-feira · 9h20 · primeira reorganização</span><h2>Marina encontra todas as informações, mas o leitor precisa caçá-las.</h2><p>P-10 exige que data e entrada sejam percebidas antes da lista de atividades. O parágrafo sobre credenciamento está depois dos agradecimentos. Mover blocos agora é mais seguro do que decorar páginas que ainda mudarão.</p></div>
      <section class="decision-box"><h3>Escolha a sequência</h3><div class="choice-list" data-choice data-answer="c" data-explanation="A sequência acompanha as perguntas reais do público: o que é, quando/onde, o que acontece e como participar."><label><input type="radio" name="d202" value="a"> agradecimentos → programação → título → entrada;</label><label><input type="radio" name="d202" value="b"> atividades em ordem alfabética, sem contexto;</label><label><input type="radio" name="d202" value="c"> título e resumo → informações essenciais → programação → orientações → contato/fonte.</label><button class="action-button" type="button" data-check-choice>Conferir sequência</button><div class="choice-result" aria-live="polite"></div></div></section>
      <h3>Executar no Writer</h3><div class="task-box"><ol><li>Na cópia <code>v01.odt</code>, ative <strong>Exibir → Navegador</strong> (ou pressione <kbd>F5</kbd>) para observar se existem títulos reconhecidos.</li><li>Selecione e recorte somente um bloco completo por vez; cole na sequência definida. Use <strong>Ctrl+Z</strong> se perder conteúdo.</li><li>Crie os rótulos textuais: “Programação”, “Orientações de entrada” e “Contato”. Ainda não altere fonte, cor ou tamanho.</li><li>Leia apenas os rótulos em ordem. Eles devem resumir o documento sem depender do corpo.</li><li>Salve como nova versão <code>..._v02.odt</code>; mantenha <code>v01</code> para comparação.</li></ol></div>
      <div class="evidence-box"><strong>Validação</strong><p>Um colega deve responder “quando?”, “onde?” e “o que ocorrerá?” em até um minuto, apontando a seção usada. Se ele depender de cor ou de sua explicação oral, a estrutura ainda não está pronta.</p></div>
      <div class="bridge-box"><strong>Consequência</strong><p>A ordem está compreensível, mas os rótulos continuam sendo texto comum aumentado manualmente. Uma mudança global exigiria edição repetida. Essa necessidade justifica estilos.</p></div>`
  },
  {
    id: 'documentos-estilos', number: '03', menuTitle: 'Estilos que mantêm consistência',
    unit: 'Módulo 2 · Documentos Profissionais', technicalTitle: 'Writer · estilos de parágrafo e manutenção',
    title: 'Formatação consistente nasce de estilos',
    objective: 'Aplicar e ajustar estilos para que estrutura, navegação e manutenção permaneçam coerentes.',
    content: `
      <div class="story-opening"><span class="eyebrow">Terça-feira · 10h00 · revisão em COORD-02</span><h2>Paulo pede que todos os subtítulos fiquem mais legíveis.</h2><p>Na minuta, cada subtítulo foi formatado separadamente. Marina poderia procurar um por um, mas isso criaria diferenças e retrabalho. Como as seções já têm função definida, elas podem compartilhar um estilo.</p></div>
      <div class="visual-lab"><div class="visual-header"><span>Representação didática de interface</span><h3>Localize função, não posição fixa</h3></div><div class="interface-strip"><span><b>Estilo atual</b> Corpo de texto</span><span><b>Escolher</b> Título 1 / Título 2</span><span><b>Gerenciar</b> F11</span><span><b>Conferir</b> Navegador</span></div><p class="visual-question"><strong>Ação:</strong> compare “aumentar fonte” com “aplicar Título 2”. Qual delas também comunica estrutura ao programa?</p></div>
      <h3>Aplicar estilos</h3><div class="task-box"><ol><li>Abra <code>v02.odt</code> e salve como <code>v03.odt</code>.</li><li>Clique no título principal e, na lista de estilos da barra ou em <strong>Estilos → Título 1</strong>, aplique <strong>Título 1</strong>.</li><li>Aplique <strong>Título 2</strong> aos rótulos de seção. Use <strong>Corpo de texto</strong> nos parágrafos comuns.</li><li>Pressione <kbd>F11</kbd>, clique com o botão direito em <strong>Título 2</strong> e escolha <strong>Editar estilo</strong>. Ajuste uma propriedade visível, como espaçamento abaixo, e confirme.</li><li>Verifique se todos os subtítulos mudaram juntos. Abra o Navegador e confirme a hierarquia.</li><li>Se um trecho mudou indevidamente, use <strong>Ctrl+Z</strong> e confira se selecionou o estilo correto, não “Título” ou “Subtítulo”.</li></ol></div>
      <div class="evidence-box"><strong>Evidência</strong><p>O Navegador lista as seções e uma alteração no estilo se propaga para todas as ocorrências. Aparência semelhante sem navegação estruturada não satisfaz o critério.</p></div>
      <details class="sources-box"><summary>Fonte oficial consultada</summary><p><a href="https://help.libreoffice.org/latest/pt-BR/text/swriter/01/05130000.html" target="_blank" rel="noopener">Ajuda do LibreOffice — Estilos no Writer</a>.</p></details>
      <div class="bridge-box"><strong>Consequência</strong><p>Com a hierarquia controlada, a equipe pode definir o espaço físico da entrega A4 sem empurrar conteúdo com linhas vazias.</p></div>`
  },
  {
    id: 'documentos-pagina', number: '04', menuTitle: 'Página, margens e cabeçalho',
    unit: 'Módulo 2 · Documentos Profissionais', technicalTitle: 'Layout · página, quebras, cabeçalho e rodapé',
    title: 'A página é uma regra de saída, não um conjunto de espaços',
    objective: 'Configurar página e elementos repetidos sem alinhar conteúdo com Enter ou espaços.',
    content: `
      <div class="story-opening"><span class="eyebrow">Terça-feira · 11h10 · teste de impressão</span><h2>Na impressora da secretaria, o rodapé desaparece e uma atividade fica sozinha na página seguinte.</h2><p>O conteúdo deve sair em A4, mas a minuta usava linhas vazias para “caber”. SEC-03 e COORD-02 exibem fontes de maneira semelhante; a impressora revela que aparência em uma tela não é prova de saída.</p></div>
      <h3>Configurar e prever</h3><div class="task-box"><ol><li>Salve <code>v03</code> como <code>v04</code>. Abra <strong>Formatar → Estilo de página</strong>.</li><li>Na guia de página, escolha <strong>A4</strong>, orientação <strong>Retrato</strong> e margens de <strong>2 cm</strong>. Esses valores são do projeto; não são regra universal.</li><li>Ative cabeçalho e insira “Escola Horizonte · Feira de Projetos”. Ative rodapé e use <strong>Inserir → Número da página</strong>; não digite “1”.</li><li>Remova sequências de linhas vazias usadas para mudar de página. Antes de uma seção que precisa iniciar em nova página, use <strong>Inserir → Quebra de página</strong>.</li><li>Abra <strong>Arquivo → Visualizar impressão</strong>. Conte páginas, confira cortes e volte para ajustar o conteúdo — não reduza tudo automaticamente.</li><li>Salve e anote em P-10: A4, retrato, margens 2 cm, cabeçalho e numeração automática.</li></ol></div>
      <div class="danger-box"><strong>Se houver diferença</strong><p>Confirme o tamanho do papel no documento e na caixa de impressão. Não escolha “ajustar à página” sem observar o efeito: ele pode esconder a causa reduzindo texto e tabelas.</p></div>
      <div class="bridge-box"><strong>Próximo problema</strong><p>A página está controlada, porém horários e locais continuam alinhados por tabulações. Quando um texto cresce, as colunas quebram. A necessidade agora é uma tabela real.</p></div>`
  },
  {
    id: 'documentos-tabelas', number: '05', menuTitle: 'Tabelas que organizam relações',
    unit: 'Módulo 2 · Documentos Profissionais', technicalTitle: 'Conteúdo tabular · cabeçalho, células e leitura',
    title: 'Tabela é para relacionar dados, não para desenhar a página',
    objective: 'Converter informações relacionadas em tabela simples, legível e verificável.',
    content: `
      <div class="story-opening"><span class="eyebrow">Terça-feira · 13h30 · programação revisada</span><h2>Uma atividade longa desloca todos os horários porque as colunas eram espaços.</h2><p>Para as famílias, cada linha precisa relacionar horário, atividade e local. Essa relação justifica uma tabela; o restante do documento continua em parágrafos.</p></div>
      <h3>Construir no Writer</h3><div class="task-box"><ol><li>Salve como <code>v05.odt</code>. Selecione apenas as linhas da programação e guarde uma cópia temporária abaixo, para retorno.</li><li>Use <strong>Tabela → Inserir tabela</strong>; crie <strong>3 colunas</strong> e linhas suficientes, com uma linha de cabeçalho.</li><li>Digite os cabeçalhos <strong>Horário</strong>, <strong>Atividade</strong> e <strong>Local</strong>. Transfira um registro por linha.</li><li>Não mescle células que contenham dados. Ajuste larguras arrastando divisórias e permita que textos longos quebrem dentro da célula.</li><li>Selecione a primeira linha e marque-a como cabeçalho repetido, se a tabela ocupar mais de uma página.</li><li>Compare linha a linha com a fonte. Só depois remova o bloco temporário.</li></ol></div>
      <div class="evidence-box"><strong>Conferência</strong><p>Cada atividade permanece associada a um único horário e local quando a largura da janela muda ou quando a página é impressa. Se uma linha se separar de seu significado, volte à cópia temporária e confira a transferência.</p></div>
      <div class="note-box"><strong>Limite</strong><p>Uma tabela pequena comunica relações. Uma coleção extensa que precisa de buscas, múltiplos relacionamentos e atualizações concorrentes pode exigir planilha ou banco de dados; não transforme o documento em cadastro.</p></div>
      <div class="bridge-box"><strong>Consequência</strong><p>A programação ficou estável. Falta justificar e descrever a imagem do mapa de entrada, para que ela informe em vez de apenas ocupar espaço.</p></div>`
  },
  {
    id: 'documentos-imagens', number: '06', menuTitle: 'Imagens, legenda e função',
    unit: 'Módulo 2 · Documentos Profissionais', technicalTitle: 'Mídia · inserção, ancoragem, legenda e alternativa',
    title: 'A imagem precisa responder a uma pergunta',
    objective: 'Inserir imagem com função comunicacional, fonte, legenda e alternativa textual.',
    content: `
      <div class="story-opening"><span class="eyebrow">Terça-feira · 14h20 · rota de entrada</span><h2>Lia sugere incluir o mapa simplificado da escola para reduzir filas no portão errado.</h2><p>A imagem agora tem função: mostrar entrada e espaços da Feira. Uma foto decorativa do prédio não resolveria essa necessidade e aumentaria o arquivo.</p></div>
      <section class="decision-box"><h3>Escolha o visual</h3><div class="choice-list" data-choice data-answer="a" data-explanation="Um mapa simples localiza os espaços e apoia a ação do visitante; a decoração não acrescenta evidência."><label><input type="radio" name="d206" value="a"> mapa autorizado com portão, recepção e blocos;</label><label><input type="radio" name="d206" value="b"> banco de imagens com estudantes genéricos;</label><label><input type="radio" name="d206" value="c"> textura colorida atrás da programação.</label><button class="action-button" type="button" data-check-choice>Conferir escolha</button><div class="choice-result" aria-live="polite"></div></div></section>
      <h3>Inserir e validar</h3><div class="task-box"><ol><li>Baixe o <a href="../downloads/informatica-produtividade/modulo-02/mapa-entrada-feira.svg" download>mapa didático autorizado</a> e registre sua origem em P-10.</li><li>Salve como <code>v06.odt</code>. Coloque o cursor após “Orientações de entrada” e use <strong>Inserir → Imagem</strong>.</li><li>Selecione a imagem, abra as propriedades e escolha ancoragem <strong>Como caractere</strong> para mantê-la no fluxo do texto.</li><li>Use <strong>Inserir → Legenda</strong> e escreva “Figura 1 — Entrada e espaços principais da Feira”.</li><li>Nas propriedades da imagem, preencha o texto alternativo: “Mapa com entrada pela Rua das Flores, recepção no pátio e acesso aos blocos A e B”.</li><li>Redimensione pelas alças de canto, preservando proporção. Visualize a impressão e confira se legenda e imagem permanecem juntas.</li></ol></div>
      <div class="evidence-box"><strong>Validação por tarefa</strong><p>Peça a um colega que localize o portão e o bloco B usando a imagem; depois leia o texto alternativo sem mostrar a imagem. Ambos devem sustentar a orientação, sem inventar detalhes.</p></div>
      <details class="sources-box"><summary>Fonte oficial consultada</summary><p><a href="https://help.libreoffice.org/latest/pt-BR/text/swriter/guide/captions.html" target="_blank" rel="noopener">Ajuda do LibreOffice — Utilizar legendas</a>.</p></details>
      <div class="bridge-box"><strong>Próximo problema</strong><p>O mapa está explicado, mas data, endereço e orientações vieram de fontes diferentes. Sem registro, a próxima atualização pode usar informação antiga.</p></div>`
  },
  {
    id: 'documentos-fontes', number: '07', menuTitle: 'Referências e fontes',
    unit: 'Módulo 2 · Documentos Profissionais', technicalTitle: 'Rastreabilidade · origem, data e uso',
    title: 'Toda afirmação importante precisa voltar a uma fonte',
    objective: 'Registrar fontes suficientes para conferência e atualização do documento.',
    content: `
      <div class="story-opening"><span class="eyebrow">Terça-feira · 15h05 · confirmação de conteúdo</span><h2>Renato informa um patrocinador; Paulo confirma o horário; Lia fornece o mapa.</h2><p>Essas informações não têm a mesma origem nem a mesma autoridade. “Foi alguém que mandou” não permite corrigir o documento quando surgir divergência.</p></div>
      <div class="table-wrap"><table><thead><tr><th>Informação</th><th>Fonte adequada</th><th>Registro mínimo</th></tr></thead><tbody><tr><td>horário de abertura</td><td>decisão registrada de Paulo</td><td>responsável, data e mensagem/ata</td></tr><tr><td>valor ou patrocínio</td><td>planilha conferida por Renato</td><td>arquivo, versão e aba/célula ou linha</td></tr><tr><td>mapa</td><td>arquivo autorizado por Lia</td><td>autor/origem, licença interna e data</td></tr></tbody></table></div>
      <h3>Aplicar</h3><div class="task-box"><ol><li>Salve como <code>v07.odt</code>.</li><li>No fim do documento, crie a seção “Fontes e validação” com estilo <strong>Título 2</strong>.</li><li>Para cada informação crítica, registre autor ou setor, título/descrição, data, caminho ou link autorizado e data de acesso quando pertinente.</li><li>Não transforme um link em prova suficiente: abra-o, confirme o conteúdo e registre a versão usada.</li><li>Para o documento público, mantenha somente fontes apropriadas ao público. Guarde detalhes internos completos em P-10.</li><li>Teste um item: parta da afirmação no documento e localize a fonte exata.</li></ol></div>
      <div class="danger-box"><strong>Privacidade</strong><p>Não publique endereço pessoal, telefone privado, conversa inteira ou link interno apenas para “provar” a fonte. Rastreabilidade e exposição são coisas diferentes.</p></div>
      <div class="bridge-box"><strong>Consequência</strong><p>O conteúdo já pode ser conferido. Paulo fará sugestões, mas Marina precisa distinguir comentário, alteração proposta e decisão aceita.</p></div>`
  },
  {
    id: 'documentos-revisao', number: '08', menuTitle: 'Revisão, comentários e alterações',
    unit: 'Módulo 2 · Documentos Profissionais', technicalTitle: 'Coautoria · comentários, alterações e decisão',
    title: 'Revisar não é sobrescrever silenciosamente',
    objective: 'Usar comentários e controle de alterações para discutir e decidir mudanças com rastreabilidade.',
    content: `
      <div class="story-opening"><span class="eyebrow">Quarta-feira · 8h15 · revisão em COORD-02</span><h2>Paulo quer trocar “abertura” por “acolhida”, mas não quer aprovar a programação inteira ainda.</h2><p>Se editar e salvar sobre a única cópia, a equipe perde a diferença entre sugestão e aceite. P-03 determina nova versão e responsável pela aprovação.</p></div>
      <h3>Roteiro de revisão</h3><div class="task-box"><ol><li>Marina salva <code>v07</code> como <code>..._para-revisao_v08.odt</code> em <code>20_Para_revisao</code>.</li><li>Paulo abre essa cópia e usa <strong>Editar → Registrar alterações → Registrar</strong>.</li><li>Ele substitui uma palavra e seleciona um horário ainda incerto; em seguida usa <strong>Inserir → Anotação</strong> para perguntar pela evidência.</li><li>Marina abre o arquivo e usa <strong>Editar → Registrar alterações → Gerenciar</strong>. Aceita somente a troca autorizada; mantém o horário pendente.</li><li>Responde ao comentário com a fonte ou registra que continua pendente. Não apaga o comentário antes do encaminhamento.</li><li>Salva uma nova versão e atualiza P-03: quem sugeriu, o que foi aceito/rejeitado, evidência e data.</li></ol></div>
      <div class="evidence-box"><strong>Resultado esperado</strong><p>A versão final não contém alterações “fantasmas”; P-03 permite explicar cada decisão relevante. Se todos os textos mudarem sem marcação, pare, feche sem salvar e repita em uma cópia com o registro ativado.</p></div>
      <details class="sources-box"><summary>Fontes oficiais consultadas</summary><p><a href="https://help.libreoffice.org/latest/pt-BR/text/shared/guide/redlining_enter.html" target="_blank" rel="noopener">Registrar alterações</a> e <a href="https://help.libreoffice.org/latest/pt-BR/text/shared/guide/redlining_accept.html" target="_blank" rel="noopener">aceitar ou rejeitar alterações</a>.</p></details>
      <div class="bridge-box"><strong>Próximo problema</strong><p>O texto foi aprovado, mas uma pessoa que usa leitor de tela ainda pode receber um documento sem ordem, descrição ou contraste suficiente. A aprovação de conteúdo não encerra a acessibilidade.</p></div>`
  },
  {
    id: 'documentos-acessibilidade', number: '09', menuTitle: 'Acessibilidade verificável',
    unit: 'Módulo 2 · Documentos Profissionais', technicalTitle: 'Acesso · estrutura, idioma, contraste e alternativas',
    title: 'Acessibilidade precisa ser conferida, não presumida',
    objective: 'Verificar estrutura e barreiras antes da exportação, corrigindo sem depender apenas do verificador automático.',
    content: `
      <div class="story-opening"><span class="eyebrow">Quarta-feira · 10h00 · requisito de publicação</span><h2>Uma família solicita o arquivo digital para leitura ampliada.</h2><p>Aumentar a fonte da impressão não resolve ordem de leitura, títulos, texto alternativo ou idioma. Como o público é diverso, P-10 passa a exigir inspeção humana e verificação automática.</p></div>
      <h3>Conferir no Writer</h3><div class="task-box"><ol><li>Salve uma cópia <code>..._acessibilidade_v09.odt</code>.</li><li>Pressione <kbd>Ctrl+A</kbd> e confira em <strong>Ferramentas → Idioma</strong> se o texto está em Português (Brasil); corrija somente o idioma do conteúdo.</li><li>No Navegador, confirme um único Título 1 e seções em ordem. Não pule de Título 1 para Título 3.</li><li>Abra as propriedades da imagem e confira o texto alternativo. Leia-o sem olhar a figura.</li><li>Garanta que links possuam texto significativo e que nenhuma informação dependa apenas de cor.</li><li>Use <strong>Ferramentas → Verificação de acessibilidade</strong>. Corrija cada alerta compreendido; se um aviso não se aplicar, registre a justificativa em P-10.</li><li>Navegue pelo documento apenas com teclado e faça leitura em zoom de 200%, observando sobreposição e cortes.</li></ol></div>
      <div class="note-box"><strong>Limite do verificador</strong><p>Ele encontra padrões técnicos, mas não decide se um título explica a seção, se o texto alternativo é útil ou se a linguagem está clara. A validação humana continua obrigatória.</p></div>
      <details class="sources-box"><summary>Fonte oficial consultada</summary><p><a href="https://help.libreoffice.org/latest/en-US/text/swriter/01/accessibility_check.html" target="_blank" rel="noopener">Ajuda do LibreOffice — Accessibility Check</a>.</p></details>
      <div class="bridge-box"><strong>Consequência</strong><p>O documento editável atende aos critérios. Agora é preciso produzir PDF e impressão sem confundir exportar com validar.</p></div>`
  },
  {
    id: 'documentos-pdf', number: '10', menuTitle: 'PDF, impressão e entrega',
    unit: 'Módulo 2 · Documentos Profissionais', technicalTitle: 'Saída · exportação, prova e pacote controlado',
    title: 'Exportar cria outro arquivo; não prova que ele está correto',
    objective: 'Gerar, abrir, conferir e entregar PDF e impressão preservando a fonte editável.',
    content: `
      <div class="story-opening"><span class="eyebrow">Quarta-feira · 13h20 · prazo de publicação</span><h2>Paulo aprovou a versão editável, mas o PDF será o arquivo recebido pelas famílias.</h2><p>Links, quebras, imagem e fontes podem se comportar de modo diferente após exportar. A equipe só chamará de “publicado” o arquivo que foi aberto e conferido.</p></div>
      <div class="visual-lab"><div class="visual-header"><span>Representação didática de interface</span><h3>Fonte editável ≠ saída de entrega</h3></div><div class="comparison-grid"><div><strong>ODT aprovado</strong><p>mantém estrutura e edição; fica no pacote interno</p></div><div><strong>PDF validado</strong><p>é aberto separadamente e destinado ao público</p></div></div><p class="visual-question"><strong>Ação:</strong> identifique qual arquivo volta para correção se o PDF cortar a tabela.</p></div>
      <h3>Exportar e provar</h3><div class="task-box"><ol><li>Confirme em P-03 qual ODT foi aprovado. Feche outras versões para evitar exportar a janela errada.</li><li>No Writer, use <strong>Arquivo → Exportar como → Exportar como PDF</strong>.</li><li>Na caixa de PDF, mantenha marcadores/tópicos e marque <strong>PDF/UA</strong> quando o verificador estiver sem problemas críticos. Escolha somente as páginas previstas.</li><li>Salve em <code>30_Publicado</code> como <code>2026-09-08_programacao-feira_publicado_v01.pdf</code>.</li><li>Feche o Writer e abra o PDF em um leitor. Confira página por página: título, tabela, mapa, legenda, links, rodapé e seleção de texto.</li><li>Use a visualização de impressão com papel A4. Se possível, faça uma prova de uma página antes do lote.</li><li>Se divergir, não edite o PDF como fonte: corrija o ODT, gere nova versão e repita toda a conferência.</li></ol></div>
      <div class="evidence-box"><strong>Registro de entrega em P-10</strong><p>Nomes do ODT e PDF, quantidade de páginas, data da conferência, leitor usado, resultado da impressão, responsável e pendências. Mova versões encerradas conforme P-02/P-03; não apague a fonte aprovada.</p></div>
      <details class="sources-box"><summary>Fonte oficial consultada</summary><p><a href="https://help.libreoffice.org/latest/pt-BR/text/shared/01/ref_pdf_export.html" target="_blank" rel="noopener">Ajuda do LibreOffice — Exportar como PDF</a>.</p></details>
      <div class="bridge-box"><strong>Consequência</strong><p>A programação está pronta. O último passo do módulo é aplicar o mesmo método a um documento diferente sem copiar decisões que pertenciam apenas a esta entrega.</p></div>`
  },
  {
    id: 'documentos-desafio', number: '11', menuTitle: 'Desafio: guia do expositor',
    unit: 'Módulo 2 · Documentos Profissionais', technicalTitle: 'Integração · planejamento, produção, revisão e prova',
    title: 'Desafio: entregar o Guia do Expositor',
    objective: 'Produzir um novo documento profissional usando P-00 a P-03 e consolidar P-10.',
    content: `
      <div class="story-opening"><span class="eyebrow">Quinta-feira · nova solicitação da Feira</span><h2>As equipes expositoras precisam saber montagem, materiais permitidos e horário de retirada.</h2><p>Lia recebeu orientações de laboratório; Renato acrescentou regras para compras; Paulo aprova o texto. O público mudou, portanto copiar a programação e trocar o título não basta.</p></div>
      <h3>Missão</h3><div class="task-box"><ol><li>Copie P-00 e registre o novo entregável, público, ação esperada, responsáveis, prazo e critérios.</li><li>Baixe as <a href="../downloads/informatica-produtividade/modulo-02/fontes-guia-expositor.zip" download>fontes do Guia do Expositor</a> em <code>00_Entrada</code>; extraia e inventarie em P-01.</li><li>Crie a fonte em ODT dentro de <code>10_Em_trabalho</code>, seguindo nomes e versões de P-02/P-03.</li><li>Defina estrutura antes de aparência; aplique estilos, página A4, uma tabela somente onde houver relação tabular e imagem apenas se ela resolver uma necessidade.</li><li>Registre fontes, comentários e decisões. Faça verificação de idioma, hierarquia, texto alternativo, contraste e teclado.</li><li>Peça revisão de um colega: ele deve localizar três regras sem sua ajuda e apontar a fonte de uma delas.</li><li>Exporte PDF, abra separadamente, confira impressão e coloque apenas aprovados em <code>30_Publicado</code>.</li><li>Complete P-10 e relacione-o a P-03.</li></ol></div>
      <div class="check-card"><strong>Checklist de aceite</strong><ul data-checklist><li><label><input type="checkbox"> finalidade, público e critérios registrados;</label></li><li><label><input type="checkbox"> fonte preservada e versões rastreáveis;</label></li><li><label><input type="checkbox"> estrutura por estilos e página controlada;</label></li><li><label><input type="checkbox"> tabelas/imagens têm função e fonte;</label></li><li><label><input type="checkbox"> revisão e acessibilidade verificadas;</label></li><li><label><input type="checkbox"> ODT e PDF abertos, comparados e registrados.</label></li></ul><p class="check-progress" data-check-progress></p></div>
      <div class="artifact-card"><strong>P-10 consolidado</strong><span>modelo reutilizável, critérios do documento, fontes, histórico de revisão, verificação de acessibilidade e prova de exportação.</span></div>
      <div class="bridge-box"><strong>Continuidade</strong><p>O documento explica a Feira, mas Renato ainda precisa responder quanto será gasto e onde estão os desvios. Essa pergunta não cabe em parágrafos: o próximo módulo começa com os dados.</p></div>`
  }
]);
