(() => {
  'use strict';

  const MBB = window.MBBPhysics = window.MBBPhysics || {};
  const $ = (selector, root = document) => root.querySelector(selector);

  const lessonHtml = `
    <section class="physics-opening">
      <span class="lesson-kicker">Uma história para investigar</span>
      <div class="hero-box physics-story">
        <strong class="card-title">À noite, você participa de uma observação no clube de ciências. O celular aponta para a Lua e mostra sua posição; alguns minutos depois, um ponto luminoso atravessa o céu: é um satélite.</strong>
        <p>Você solta uma bolinha da mão e ela cai. A Lua não cai sobre a Terra. O satélite também não. Então surge a pergunta: <strong>por que a gravidade derruba a bolinha e, ao mesmo tempo, pode manter outros corpos em órbita?</strong></p>
        <div class="quick-question" data-choice-question data-correct="b"><strong>Antes de continuar, faça uma aposta</strong><p>Um satélite em órbita está fora do alcance da gravidade terrestre?</p><div class="choice-row"><button type="button" data-choice="a">Sim, senão cairia no chão</button><button type="button" data-choice="b">Não; a gravidade é justamente parte do que curva sua trajetória</button><button type="button" data-choice="c">Só satélites artificiais ficam sem gravidade</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Essa é a chave do começo do capítulo: órbita não significa ausência de gravidade." data-wrong-text="Lembre da aceleração centrípeta: uma trajetória curva exige mudança contínua da direção da velocidade."></div></div>
        <p class="central-question"><strong>Nossa missão:</strong> começar com uma queda simples, passar por satélites e planetas e, passo a passo, ampliar a escala até os modelos cosmológicos e a relatividade geral.</p>
      </div>
    </section>

    <section>
      <h3>1. A bolinha cai. A Lua também “cai” — mas de outro jeito</h3>
      <p>A Terra atrai a bolinha, a Lua e o satélite. O que muda entre uma queda perto do chão e uma órbita é a combinação entre <strong>gravidade e velocidade</strong>.</p>
      <p>Imagine lançar um objeto horizontalmente de uma grande altura. Com pouca velocidade, ele atinge o chão logo adiante. Se a velocidade horizontal for muito maior e desconsiderarmos obstáculos e atmosfera, enquanto o objeto cai a superfície curva da Terra também “se afasta” abaixo dele. Em uma condição orbital, ele permanece em <strong>queda contínua ao redor da Terra</strong>.</p>
      <div class="note-box"><strong>Astronauta flutuando não significa gravidade zero</strong><p>A estação e o astronauta estão caindo juntos ao redor da Terra. O que praticamente desaparece é a força normal de apoio que sentimos quando estamos parados no chão.</p></div>
      <div class="quick-question" data-choice-question data-correct="c"><strong>Explique com o que já sabe</strong><p>Por que uma órbita exige aceleração mesmo que o módulo da velocidade seja aproximadamente constante?</p><div class="choice-row"><button type="button" data-choice="a">Porque o tempo para</button><button type="button" data-choice="b">Porque a massa aumenta</button><button type="button" data-choice="c">Porque a direção da velocidade muda continuamente</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Velocidade é vetorial: mudar direção é acelerar." data-wrong-text="Retome a rotatória e o movimento circular dos capítulos anteriores."></div></div>
    </section>

    <section>
      <h3>2. Mas a gravidade fica igual em qualquer distância?</h3>
      <p>O aplicativo mostra a Lua a cerca de centenas de milhares de quilômetros da Terra. Se a gravidade ainda atua, ela precisa ser descrita de modo que a distância importe.</p>
      <p>Newton formulou uma relação que conecta as massas dos corpos e a distância entre seus centros.</p>
      <div class="equation-walk"><div><span>1</span><p>Mais massa em qualquer um dos corpos → interação gravitacional maior.</p></div><div><span>2</span><p>Maior distância → interação menor.</p></div><div><span>3</span><p>A queda com a distância é forte: depende de <strong>r²</strong>.</p></div></div>
      <div class="formula-box"><span class="formula-name">Lei da Gravitação Universal</span><div class="big-formula">F = G · m₁ · m₂ / r²</div><p><strong>G</strong> é a constante gravitacional e r é a distância entre os centros dos corpos.</p></div>
      <div class="quick-question" data-choice-question data-correct="c"><strong>Faça a previsão antes da conta</strong><p>Se a distância dobra e as massas não mudam, a força gravitacional passa a ser:</p><div class="choice-row"><button type="button" data-choice="a">duas vezes maior</button><button type="button" data-choice="b">metade</button><button type="button" data-choice="c">um quarto</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Dobrar r torna r² quatro vezes maior; a força cai para 1/4." data-wrong-text="Observe o quadrado no denominador."></div></div>
    </section>

    <section>
      <h3>3. O telescópio muda de alvo: agora você acompanha um planeta</h3>
      <p>Durante séculos, astrônomos registraram posições planetárias. Johannes Kepler encontrou padrões nesses dados antes de Newton fornecer uma explicação gravitacional mais geral.</p>
      <p>Isso é importante para entender como ciência funciona: primeiro observamos regularidades; depois procuramos modelos capazes de explicá-las e fazer novas previsões.</p>
      <div class="three-col"><div class="example-box"><strong class="card-title">1ª lei</strong><p>Os planetas descrevem órbitas elípticas, com o Sol em um dos focos.</p></div><div class="example-box"><strong class="card-title">2ª lei</strong><p>A linha planeta–Sol varre áreas iguais em tempos iguais. O planeta se move mais rápido nas regiões mais próximas do Sol.</p></div><div class="example-box"><strong class="card-title">3ª lei</strong><p>Para corpos orbitando o mesmo centro, órbitas maiores têm períodos maiores.</p></div></div>
      <div class="formula-box"><span class="formula-name">Forma proporcional da 3ª lei para o mesmo corpo central</span><div class="big-formula">T² ∝ a³</div><p>T é o período orbital e a é o semieixo maior da órbita.</p></div>
      <div class="example-box"><strong class="card-title">Leitura proporcional</strong><p>Se a distância orbital característica for 4 vezes maior, então T² cresce por 4³ = 64. Assim, T cresce por √64 = <strong>8 vezes</strong>.</p></div>
    </section>

    <section>
      <h3>4. Agora você usa o celular como laboratório de órbitas</h3>
      <p>Vamos manter o mesmo corpo central e variar apenas uma distância orbital relativa. O objetivo não é reproduzir um planeta real específico, mas enxergar três relações: a atração diminui com 1/r², a velocidade orbital circular diminui aproximadamente com 1/√r e o período cresce com r<sup>3/2</sup>.</p>
      <div class="interactive-lab" id="orbitLab"><div class="lab-heading"><span class="lesson-kicker">Laboratório interativo</span><h4>Afaste a órbita e faça uma previsão antes de olhar os números</h4></div><div class="lab-controls"><label>Distância orbital relativa <strong><span id="orbitRadiusValue">1,00</span> r</strong><input id="orbitRadiusRange" type="range" min="1" max="5" step="0.25" value="1"></label></div><svg class="lesson-visual" id="orbitLabSvg" viewBox="0 0 760 300" role="img" aria-label="Simulação de uma órbita circular cuja distância pode ser alterada"><circle cx="380" cy="150" r="32" fill="#f6c453"/><circle id="orbitPath" cx="380" cy="150" r="70" fill="none" stroke="#aab9ca" stroke-width="3" stroke-dasharray="8 7"/><circle id="orbitPlanet" cx="450" cy="150" r="13" fill="#1967d2"/><text x="350" y="158" class="visual-note">Sol</text></svg><div class="lab-result" aria-live="polite"><span>Força gravitacional relativa:</span><strong id="relativeGravityValue">1,00</strong><span>Velocidade orbital relativa:</span><strong id="relativeSpeedValue">1,00</strong><span>Período orbital relativo:</span><strong id="relativePeriodValue">1,00</strong></div><p id="orbitConclusion">Perto do corpo central, a atração é mais intensa e o período orbital é menor.</p></div>
    </section>

    <section>
      <h3>5. A noite avança e alguém pergunta: “e o Universo inteiro, sempre foi assim?”</h3>
      <p>A escala da pergunta mudou completamente. Agora não estamos tratando apenas de um planeta em torno do Sol, mas da evolução do próprio Universo.</p>
      <p>O modelo cosmológico do <strong>Big Bang</strong> descreve um Universo que, no passado, esteve em um estado extremamente quente e denso e que se expandiu e evoluiu ao longo do tempo.</p>
      <div class="note-box"><strong>Big Bang não é uma bomba explodindo num ponto do espaço</strong><p>Essa imagem é enganosa. No modelo cosmológico, é o próprio espaço em grande escala que evolui e se expande; não precisamos imaginar uma explosão comum dentro de um espaço vazio já existente.</p></div>
      <div class="quick-question" data-choice-question data-correct="b"><strong>Qual descrição é melhor?</strong><p>O Big Bang, em nível introdutório, é melhor entendido como:</p><div class="choice-row"><button type="button" data-choice="a">uma explosão comum a partir de um ponto central do espaço</button><button type="button" data-choice="b">a evolução de um Universo antes muito quente e denso, com expansão do espaço em grande escala</button><button type="button" data-choice="c">uma única galáxia que se partiu em todas as outras</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Essa formulação evita a analogia inadequada de uma bomba no espaço." data-wrong-text="Pense no próprio espaço participando da expansão."></div></div>
    </section>

    <section>
      <h3>6. Como sabemos que o Universo está se expandindo?</h3>
      <p>Modelos científicos não são aceitos porque “parecem bonitos”. Eles precisam se relacionar com observações. Em cosmologia, diferentes linhas de evidência sustentam a ideia de um Universo em expansão que teve um passado quente e denso.</p>
      <div class="three-col"><div class="example-box"><strong class="card-title">Galáxias distantes</strong><p>Em grande escala, seus espectros mostram um padrão compatível com expansão cosmológica.</p></div><div class="example-box"><strong class="card-title">Radiação cósmica de fundo</strong><p>Uma radiação muito antiga permeia o Universo e é uma evidência importante de um passado quente e denso.</p></div><div class="example-box"><strong class="card-title">Elementos leves</strong><p>As abundâncias observadas de certos elementos leves são compatíveis com previsões sobre processos do Universo primordial.</p></div></div>
      <div class="note-box"><strong>Uma analogia com limite</strong><p>Pontos desenhados num balão que infla podem ajudar a visualizar distâncias crescendo entre muitos pontos. Mas o Universo não precisa ser literalmente a superfície de um balão, nem a analogia deve ser levada além do que ela ajuda a representar.</p></div>
    </section>

    <section>
      <h3>7. Então Newton estava errado?</h3>
      <p>Essa pergunta aparece naturalmente quando chegamos à <strong>relatividade geral</strong>. Einstein descreveu gravidade de forma mais abrangente, relacionando massa e energia à geometria do espaço-tempo.</p>
      <p>Isso não transforma a Física de Newton em algo inútil. Em muitas situações do cotidiano, engenharia e órbitas simples, a descrição newtoniana é uma excelente aproximação. A relatividade se torna necessária quando precisamos de maior precisão ou lidamos com campos gravitacionais intensos e escalas cosmológicas.</p>
      <div class="two-col"><div class="example-box"><strong class="card-title">Newton</strong><p>Gravidade tratada como interação entre massas; modelo muito eficiente em grande variedade de situações.</p></div><div class="example-box"><strong class="card-title">Einstein</strong><p>Gravidade descrita pela geometria do espaço-tempo; teoria mais geral.</p></div></div>
      <div class="quick-question" data-choice-question data-correct="c"><strong>Modelos científicos</strong><p>Por que ainda usamos Newton se existe a relatividade geral?</p><div class="choice-row"><button type="button" data-choice="a">Porque a relatividade foi abandonada</button><button type="button" data-choice="b">Porque Newton explica absolutamente tudo</button><button type="button" data-choice="c">Porque Newton é uma aproximação excelente em muitos domínios</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Modelos têm domínios de validade e níveis de precisão diferentes." data-wrong-text="Uma teoria mais geral não apaga automaticamente modelos úteis em seus domínios."></div></div>
    </section>

    <section>
      <h3>8. O céu que você observou no começo agora parece outro</h3>
      <p>A Lua, o satélite, os planetas e as galáxias não são assuntos desconectados. A Física constrói modelos em diferentes escalas: queda e movimento orbital; leis empíricas de Kepler; gravitação de Newton; expansão cosmológica; relatividade geral.</p>
      <p>O mais importante não é decorar uma sequência de nomes, mas perceber como cada modelo responde a uma pergunta e quais observações ele consegue explicar.</p>
      <div class="note-box"><strong>Pare e explique em suas palavras</strong><p>Como a mesma palavra “gravidade” pode aparecer numa bolinha caindo, numa Lua em órbita e numa teoria sobre espaço-tempo sem que sejam exatamente a mesma descrição matemática?</p><details><summary>Compare sua ideia</summary><p>O fenômeno gravitacional aparece em escalas diferentes. Newton fornece uma descrição extremamente útil para muitos movimentos; a relatividade geral amplia essa descrição ao relacionar gravidade à geometria do espaço-tempo.</p></details></div>
    </section>

    <section>
      <h3>9. Experimento de mesa: construa uma elipse antes de falar em órbitas elípticas</h3>
      <div class="experiment-box"><strong class="card-title">Barbante, dois focos e lápis</strong><ol class="reason-steps"><li>Prenda dois pontos numa folha sobre uma base adequada.</li><li>Faça um laço de barbante envolvendo os dois pontos.</li><li>Mantenha o barbante esticado com um lápis e percorra a curva.</li><li>Observe que a elipse possui dois focos.</li><li>Compare com a 1ª lei de Kepler: o Sol ocupa um dos focos da órbita idealizada.</li></ol><p class="safety-note"><strong>Segurança:</strong> use material escolar adequado e evite pontas expostas ou superfícies que possam ser danificadas.</p></div>
    </section>

    <section class="chapter-checkpoint">
      <span class="lesson-kicker">Antes de guardar o telescópio</span>
      <h3>10. Você consegue ligar queda, órbitas e Universo?</h3>
      <div class="quick-question" data-choice-question data-correct="c"><strong>1. Distância</strong><p>Se a distância entre dois corpos triplica, mantendo as massas, a força gravitacional fica:</p><div class="choice-row"><button type="button" data-choice="a">3 vezes maior</button><button type="button" data-choice="b">1/3</button><button type="button" data-choice="c">1/9</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="F ∝ 1/r²." data-wrong-text="Triplique r e depois eleve ao quadrado."></div></div>
      <div class="quick-question" data-choice-question data-correct="b"><strong>2. Satélite</strong><p>Um satélite em órbita:</p><div class="choice-row"><button type="button" data-choice="a">está sem gravidade</button><button type="button" data-choice="b">está em queda contínua ao redor da Terra</button><button type="button" data-choice="c">não possui velocidade</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="A gravidade curva a trajetória." data-wrong-text="Órbita não significa ausência de gravidade."></div></div>
      <div class="quick-question" data-choice-question data-correct="a"><strong>3. Kepler 1</strong><p>Na primeira lei, o Sol fica:</p><div class="choice-row"><button type="button" data-choice="a">em um dos focos da elipse</button><button type="button" data-choice="b">sempre no centro geométrico</button><button type="button" data-choice="c">fora da órbita</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Essa é a característica central da 1ª lei." data-wrong-text="Uma elipse possui dois focos."></div></div>
      <div class="quick-question" data-choice-question data-correct="c"><strong>4. Kepler 2</strong><p>O planeta se move mais rapidamente quando:</p><div class="choice-row"><button type="button" data-choice="a">a velocidade nunca muda</button><button type="button" data-choice="b">está mais longe</button><button type="button" data-choice="c">está mais perto do Sol</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="A lei das áreas implica maior rapidez perto do Sol." data-wrong-text="Pense em áreas iguais em tempos iguais."></div></div>
      <div class="quick-question" data-choice-question data-correct="b"><strong>5. Kepler 3</strong><p>Em torno do mesmo corpo central, órbita maior tende a ter:</p><div class="choice-row"><button type="button" data-choice="a">período menor</button><button type="button" data-choice="b">período maior</button><button type="button" data-choice="c">período zero</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="T² ∝ a³." data-wrong-text="Aumente a e observe T."></div></div>
      <div class="quick-question" data-choice-question data-correct="b"><strong>6. Big Bang</strong><p>Qual descrição é adequada?</p><div class="choice-row"><button type="button" data-choice="a">uma bomba num ponto central do espaço vazio</button><button type="button" data-choice="b">evolução de um Universo antes muito quente e denso, com expansão em grande escala</button><button type="button" data-choice="c">uma galáxia se dividiu em todas as outras</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Essa formulação corresponde melhor ao modelo introdutório." data-wrong-text="Evite a analogia da explosão comum."></div></div>
      <div class="quick-question" data-choice-question data-correct="c"><strong>7. Newton e Einstein</strong><p>Por que Newton continua útil?</p><div class="choice-row"><button type="button" data-choice="a">porque Einstein foi descartado</button><button type="button" data-choice="b">porque Newton é exato em qualquer situação</button><button type="button" data-choice="c">porque é uma excelente aproximação em muitos domínios</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Modelos podem continuar úteis dentro de seus domínios." data-wrong-text="Pense em aproximação e precisão necessária."></div></div>
      <div class="quick-question" data-choice-question data-correct="a"><strong>8. Relatividade geral</strong><p>Em nível introdutório, ela relaciona gravidade à:</p><div class="choice-row"><button type="button" data-choice="a">geometria do espaço-tempo</button><button type="button" data-choice="b">ausência de movimento</button><button type="button" data-choice="c">inexistência de massa</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="A geometria do espaço-tempo é central nessa descrição." data-wrong-text="Retome a comparação Newton–Einstein."></div></div>
      <div class="challenge-box"><strong>Desafio MbB — volte ao começo da noite</strong><p>Explique por que o astronauta parece flutuar mesmo sob ação da gravidade. Sua resposta precisa usar queda contínua, velocidade tangencial e órbita. Depois ligue essa explicação ao fato de a Lua não “ficar parada” no céu: ela também está em movimento orbital.</p></div>
    </section>

    <details class="curriculum-box"><summary>Conexão com o plano de curso</summary><p>O capítulo trabalha os objetos previstos de <strong>Astronomia e Universo</strong>: Big Bang, expansão do Universo, leis de Kepler, gravitação universal, modelos cosmológicos e relatividade geral. A noite de observação funciona como fio condutor para ligar queda, órbitas e cosmologia.</p></details>
  `;

  function initOrbitLab(root){
    const radius=$('#orbitRadiusRange',root),radiusValue=$('#orbitRadiusValue',root),gravityValue=$('#relativeGravityValue',root),speedValue=$('#relativeSpeedValue',root),periodValue=$('#relativePeriodValue',root),path=$('#orbitPath',root),planet=$('#orbitPlanet',root),conclusion=$('#orbitConclusion',root);
    if(!radius||!radiusValue||!gravityValue||!speedValue||!periodValue||!path||!planet||!conclusion)return;
    const format=(v,d=2)=>Number(v).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});
    const draw=()=>{const r=Number(radius.value),force=1/(r*r),speed=1/Math.sqrt(r),period=Math.pow(r,1.5); radiusValue.textContent=format(r); gravityValue.textContent=format(force); speedValue.textContent=format(speed); periodValue.textContent=format(period); const visualRadius=55+((r-1)/4)*110; path.setAttribute('r',visualRadius.toFixed(1)); planet.setAttribute('cx',(380+visualRadius).toFixed(1)); planet.setAttribute('cy','150'); conclusion.textContent=r<2?'Mais perto do corpo central, a atração é mais intensa, a velocidade orbital circular é maior e o período é menor.':r<4?'Ao afastar a órbita, a atração cai com 1/r² e o período cresce conforme r^(3/2).':'Em uma órbita bem mais distante, a atração é muito menor e o tempo para completar uma volta é muito maior.';};
    radius.addEventListener('input',draw); draw();
  }

  MBB.enableChapter?.('08 Da queda de uma maçã ao Universo',()=>{MBB.showLesson({unit:'Terra e Cosmos',technical:'Astronomia • Big Bang • expansão do Universo • Kepler • gravitação universal • modelos cosmológicos • relatividade geral',title:'Da queda de uma maçã ao Universo',objective:'<strong>Propósito:</strong> acompanhar uma noite de observação para conectar queda e órbita e compreender como Kepler, Newton e a cosmologia moderna descrevem movimentos e a evolução do Universo.',html:lessonHtml,init:initOrbitLab});});
})();